name: SmartUI Monorepo GitHub Actions

on:
  workflow_dispatch:
    inputs:
      project_token_1:
        description: Project Token - SDK
        required: true
      project_token_2:
        description: Project Token - Storybook
        required: true

env:
  LT_USERNAME: ${{ secrets.LT_USERNAME }}
  LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}

jobs:
  smartui_tests:
    name: Execute SmartUI Tests - Monorepo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Execute SmartUI SDK tests
      - name: Install dependencies
        run: |
          cd sdk
          npm i @lambdatest/smartui-cli

      - name: Running Commands
        env:
          PROJECT_TOKEN: ${{ github.event.inputs.project_token_1 }}
        run: |
          npx smartui --version
          npx smartui config:create smartui-web.json
          npx smartui --config smartui-web.json exec -- mvn --quiet test -D suite=sdk-cloud.xml
      
      - name: Execute SmartUI Storybook tests
      - name: Install dependencies
        run: |
          cd ../storybook
          npm install @lambdatest/smartui-storybook -g
          npm i @lambdatest/smartui-cli

      - name: Running Commands
        env:
          PROJECT_TOKEN: ${{ github.event.inputs.project_token_2 }}
        run: |
          npx smartui --version
          npx smartui config:create smartui-web.json
          npm run build-storybook
          smartui storybook ./storybook-static --config .smartui.json
